//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lib_Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public articulo()
        {
            this.articulo_pedido = new HashSet<articulo_pedido>();
        }
    
        public int id_articulo { get; set; }
        public string nombre_articulo { get; set; }
        public string descripcion { get; set; }
        public int cantidad_disponible { get; set; }
        public string estado_articulo { get; set; }
        public int precio { get; set; }
        public string url_imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<articulo_pedido> articulo_pedido { get; set; }
    }
}
